AllCops:
  Exclude:
    - 'app/test/**/*'
    - 'app/bin/**/*'
    - 'app/db/**/*'
    - 'app/config/**/*'
    - 'app/Gemfile'

Style/GuardClause:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30
