development:
  adapter: mysql2
  encoding: utf8
  database: moestock
  username: root
  password:
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: ENV['DB_NAME']
  username: ENV['DB_USER']
  password: ENV['DB_PW']
  host: ENV['DB_HOST']
  port: 3306
