development:
  adapter: mysql2
  encoding: utf8
  database: galgame
  username: root
  password: Cn19870417
  host: 192.168.65.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: galgame
  username: root
  password: Cn19870417
  host: 192.168.65.1
  port: 3306
