require 'sinatra'
require 'sinatra/reloader' if development?
require 'sinatra/activerecord'
require 'sinatra/cookies'
require 'i18n'
require 'i18n/backend/fallbacks'
require 'securerandom'
require './lib/random'
require './config/settings'
require './models/user'
require './models/stock'
require './apis/user'
require './apis/stock'
