source 'http://gems.ruby-china.org'

# CORE
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'

# DB
gem 'mysql2'
gem 'sinatra-activerecord'

# ETC
gem 'bcrypt', '~> 3.1.7'
gem 'rake'
gem "activesupport"

gem 'pry'
