require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require './app'
  end
end

namespace :stock do
  task :init do
    require './app'
    Stock.create(
      code: 'ERIRI',
      name: '泽村·斯宾塞·英梨梨',
      avatar: '/static/images/eriri.gif'
    )
    Stock.create(
      code: 'ERIRI',
      name: '泽村·斯宾塞·英梨梨',
      avatar: '/static/images/eriri.gif'
    )
    Stock.create(
      code: 'UTAHA',
      name: '霞之丘诗羽',
      avatar: '/static/images/utaha.gif'
    )
    Stock.create(
      code: 'KM',
      name: '加藤惠',
      avatar: '/static/images/kato.gif'
    )
  end
end
